### ISSUE TITLE
"Load Msgs" button is broken

### ISSUE THREAD

**Issue by teamvista** [BNolet/RLC#108] opened 2016-04-29 23:49 UTC
Using v.2.29. Intended behavior is to load previous messages from history; does not load messages at all.

**Comment by LewisMCYoutube** [comment] 2016-04-30 09:33
works as intended

**Comment by Stjerneklar** [comment] 2016-04-30 10:36
fixed in 2.29.34

**Closed as completed by Stjerneklar** 2016-04-30 10:36 UTC

**Comment by LewisMCYoutube** [comment] 2016-04-30 10:41
cool
