### ISSUE TITLE
List of Issues(and requests) for me(Windows 10/Firefox-TTS enabled/Lenovo G50 laptop)

### ISSUE THREAD

**Issue by kretenkobr2** [BNolet/RLC#100] opened 2016-04-29 09:56 UTC
Here we go for the list:
1. ~~Refreshing page reads all the messages starting from 10th message from top moving upwards.(probably due to message order actually not being changed from top being newest message and only display showing them reversed) **CONSISTENT** but not always reads ALL the messages, sometimes only reads 8 of 10(9/10 times reads ALL the messages)~~
2. ~~Enabling User Based Voices completely disables TTS. **CONSISTENT**~~
3.  ~~/me messages have "said XYZ" in them. **CONSISTENT** might be because of 7.~~
4. Sometimes does not read messages at all even though the message does not have 3 letters in a row. **HIGHLY INCONSISTENT** only been able to  produce it 1 times had at least 10 tries. <<---- **should ignore this, no way to replicate or test it, but keep it in mind**
5. ~~on refresh when using 24 hour timestamps - 10 latest messages (again) all latest messages(latest on refresh) are showed in 12 hour time stamps; newer ones are showed in 24 hour time stamps, as well as the older messages **CONSISTENT**~~
6. ~~If you refresh more times quickly it reads messages really really randomly as it would read every message starting from 10th from top moving upwards and pretty much reads all for every refresh you make(aka. if you refresh 5 times it will read all the messages randomly but will read every message 5 times) - just made it happen when I tested timespamps' consistency **CONSISTENT**~~
7. ~~It pronounces my name wrongly and weirdly, it pronounces my name as **kretenkobr-twou**. **CONSISTENT** pronounces the two as twou... Weird as hell... also kretenkobrtwo does not work, only works when T in two is capital :/~~
8. ~~D: smiley is not shown if used alone although _No Emotes_ in the options is not checked(_I realized that distance between D: and other emotes is smaller than that of other emotes between each other,specifically the space after the D: emote_) (also D: is not shown if it is at the end of the message <--kinda tested, didn't feel like testing it fully, would be pretty spammish on already spammy day)  **CONSISTENT**~~
9. ~~"<" stops every sound after it, even the "said X" thing, message just stops after the sign, nothing after it is read **CONSISTENT**~~ **WHY IS FUCKING "<" PRONOUNCED AS KLEINERDONG FFS!?**

Hope this list helps you solve the problems :D CHEERS

**Comment by kretenkobr2** [comment] 2016-04-29 17:32
no.1 has been solved as well as no. 6 due to it being it's "evil son"

**Comment by kretenkobr2** [comment] 2016-04-29 19:36
no. 2 solved(kindof)

**Comment by mofosyne** [comment] 2016-04-29 19:44
For problem number 3

in

```
                    case /^[\\\/]me/.test(checkingStr): //Check for declared action
                        var msg = new SpeechSynthesisUtterance( $usr.text() + " " + linetoread  + toneStr  );
                        break;
```

the regexp should be

`/^[\\\/]me .+/`

**Comment by Stjerneklar** [comment] 2016-04-30 11:58
3 solved

**Comment by LewisMCYoutube** [comment] 2016-05-01 17:04
😀 😬 😁 😂 😃 😄 😅 😆 😇 😉 😊 🙂 🙃 ☺️ 😋 😌 😍 😘 😗 😙 😚 😜 😝 😛 🤑 🤓 😎 🤗 😏 😶 😐 😑 😒 🙄 🤔 😳 😞 😟 😠 😡 😔 😕 🙁 ☹️ 😣 😖 😫 😩 😤 😮 😱 😨 😰 😯 😦 😧 😢 😥 😪 😓 😭 😵 😲 🤐 😷 🤒 🤕 😴 💤 💩 😈 👿 👹 👺 💀 👻 👽 🤖 😺 😸 😹 😻 😼 😽 🙀 😿 😾 🙌 👏 👋 👍 👊 ✊ ✌️ 👌 ✋ 💪 🙏 ☝️ 👆 👇 👈 👉 🖕 🤘 🖖 ✍️ 💅 👄 👅 👂 👃 👁 👀 👤 🗣 👶 👦 👧 👨 👩 👱 👴 👵 👲 👳 👮 👷 💂 🕵 🎅 👼 👸 👰 🚶 🏃 💃 👯 👫 👬 👭 🙇 💁 🙅 🙆 🙋 🙎 🙍 💇 💆 💑 👩‍❤️‍👩 👨‍❤️‍👨 💏 👩‍❤️‍💋‍👩 👨‍❤️‍💋‍👨 👪 👨‍👩‍👧 👨‍👩‍👧‍👦 👨‍👩‍👦‍👦 👨‍👩‍👧‍👧 👩‍👩‍👦 👩‍👩‍👧 👩‍👩‍👧‍👦 👩‍👩‍👦‍👦 👩‍👩‍👧‍👧 👨‍👨‍👦 👨‍👨‍👧 👨‍👨‍👧‍👦 👨‍👨‍👦‍👦 👨‍👨‍👧‍👧 👚 👕 👖 👔 👗 👙 👘 💄 💋 👣 👠 👡 👢 👞 👟 👒 🎩 ⛑ 🎓 👑 🎒 👝 👛 👜 💼 👓 🕶

**Comment by mofosyne** [comment] 2016-05-03 18:13
7 is fixed?

**Comment by kretenkobr2** [comment] 2016-05-03 18:20
7 not fixed to me :'( T_T ;_;

**Comment by kretenkobr2** [comment] 2016-05-03 18:38
for 5 maybe:(Stjerneklar)

```
function convertTo24Hour(time)
{
var hours = parseInt(time.substr(0, 2));
if (time.indexOf("am") !== -1 && hours === 12) time = time.replace("12", "0");
if (time.indexOf("pm") !== -1 && hours < 12) time = time.replace(hours, (hours + 12));
return time.replace(/(am|pm)/, "");
} 
```

**Comment by mofosyne** [comment] 2016-05-03 18:48
Whats your preferred spelling to use instead. Can you test using your tts, then give us your desired spelling?

**Comment by kretenkobr2** [comment] 2016-05-03 18:56
> Whats your preferred spelling to use instead. Can you test using your tts, then give us your desired spelling?

KretenkobrTwo works always, but I don't know why doesn't it want to switch Kretenkobr2 with KretenkobrTwo also kretenkobrtwo does not work, don't know why

**Comment by Stjerneklar** [comment] 2016-05-04 04:31
issue 5 should be fixed since v3.7.10(at least it appears so on my pc). 

issues 7 & 9 appear to be caused by Kretens "Zira" text to speech voice, which speaks all voices for him. 

issue 7 has had specific code written to cause RLC to tell text to speech to pronounce kretens name as he wants it, however the problem still persists for him.

further work in this area should focus on figuring out if we can force this "Zira" voice not to be used.

**Comment by kretenkobr2** [comment] 2016-05-04 12:55
5 fully fixed yap :D 

7 and 9 are not though, and I ma pretty sure it is not Zira thing... mofosyne's voice is some Microsoft "Mike" I think as opposed to MS "Zira" and it still pronounces my name incorrectly... It might be some switch thing, where it fails to replace my name with "KretenkobrTwo", ~~might be because "Kretenkobr2" it is my username and therefore it somehow cannot replace it with something else...~~ it is actually because of numbers, tested it, "N1" to "nice one" also doesn't work because it of number...

don't know about 9... seems weird

**Comment by kretenkobr2** [comment] 2016-05-04 14:12
7 fixted

**Comment by kretenkobr2** [comment] 2016-05-04 19:17
9 solved... kinda...

**Comment by Stjerneklar** [comment] 2016-05-04 19:58
thanks for the reports :) 
please use seperate posts in the future though

**Closed as completed by Stjerneklar** 2016-05-04 19:58 UTC
Labels: RLC bug
