### ISSUE TITLE
Option to not display seconds in timestamps

### ISSUE THREAD

**Issue by UnderTheHole** [BNolet/RLC#255] opened 2016-05-14 19:05 UTC
Currently on RLC v3.16.2, which is the branch testing. 

I don't know if it occurs by region, but I have the "bug" and couple of others too. However, Stjernklar doesn't have it which I think is because he's using 24 hour time. 

I have 12 hour time. I use PST, if that helps. 

Here's a screenshot: http://puu.sh/oROfy/944d737050.png

**Comment by Stjerneklar** [comment] 2016-05-15 06:47
i must be using the wrong date function in the timeandusertracking section, will revise.

**Comment by Stjerneklar** [comment] 2016-05-15 08:36
fix attempted in 3.16.6, merged to testing branch

**Comment by Stjerneklar** [comment] 2016-05-15 09:13
times should now be in 24 hour. guess i can add option to show times as 12 hour...

**Comment by kretenkobr2** [comment] 2016-05-15 12:10
this is not a bug, why shouldn't they show sec's?

**Comment by dashed** [comment] 2016-05-15 12:28
Compromise by having option to hide the seconds.

**Closed as completed** 2016-05-21 13:30 UTC
Labels: Feature request
