### ISSUE TITLE
Long names split into two lines

### ISSUE THREAD

**Issue by FlamingObsidian** [BNolet/RLC#48] opened 2016-04-18 21:38 UTC
My name (the long number) splits in two.

**Comment by touya-akira** [comment] 2016-04-18 22:06
happens to a few nicks as well, but at some point is not preventable. Consider users (like me) who use Ctrl-+ to zoom in a bit, too.

**Comment by Stjerneklar** [comment] 2016-04-19 15:49
always open to suggestions on better ways to display the messages, but for now im going to close this issue since it is working as intended.

**Closed as completed by Stjerneklar** 2016-04-19 15:49 UTC
